export const ACTIONS = {
  AUTO_REFRESH: 'AUTO_REFRESH',
  REPEAT_STAGE: 'REPEAT_STAGE',
};

export const PAGE_TYPE = {
  NULL: '',
  HOME: 'HOME',
  QUEST: 'QUEST',
  SUPPORTER: 'SUPPORTER',
  RAID: 'RAID',
  RESULT: 'RESULT',
};
